# Generated by Django 3.1.4 on 2021-01-01 03:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started', models.DateTimeField(auto_created=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('img', models.URLField()),
                ('back_img', models.URLField()),
                ('slug', models.SlugField(max_length=255)),
                ('project_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_type', to='project.projecttype')),
            ],
        ),
    ]
